# genai_lib — Projektbibliothek für den Agenten-Kurs
#
# Submodule:
#   from genai_lib.utilities    import mprint, mermaid, setup_api_keys, ...
#   from genai_lib.model_config import BASELINE, WORKER, JUDGE, ...
#   from genai_lib.briefing_rag import get_briefing_vectorstore, index_briefing_corpus, make_suche_wissensdatenbank_tool
